### PR TITLE
add "Don't worry, I have a masters degree/Ph.D in" cards

### PR DESCRIPTION
**Pull request by omnidan**

### CODE REVIEW

**Comment by nyuszika7h** [comment]
It's "master's degree", and either "Ph.D." or "PhD".

**Comment by omnidan** [comment]
@nyuszika7h also this should go to https://github.com/ircah/irc-against-humanity right? why's the format different?

**Comment by nyuszika7h** [comment]
Wrong repo. This is for the official CAH Base Set. You should submit this to ircah/irc-against-humanity instead.

**Comment by nyuszika7h** [comment]
The format is different because @michealharker decided to rewrite the bot again, and this will be used for the new bot, ask him why he changed it.

**Comment by omnidan** [comment]
@nyuszika7h so one of the sets isn't being used right now?

**Comment by nyuszika7h** [comment]
No, this set [is in the cah-js repo](https://github.com/ircah/cah-js/blob/master/sets/base_set.json). The separate repo architecture for sets will be used by the new bot.

**Pull request closed without merging**
